<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\SoftDeletes;

class Article extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'title',
        'text',
        'image',
        'category_id',
        'user_id',
    ];

    protected static function boot()
    {
        static::creating(function ($model) {
            $model->user_id = auth()->id();
        });

        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function categories(): BelongsToMany
    {
        return $this->belongsToMany(Category::class);
    }
}
